backend:
  name: git-gateway
  branch: main

locale: 'fr'
media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "landing1"
    label: "Landing1"
    folder: "landing1"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}